image: node:lts-alpine3.14

stages:
  - prepare
  - build
  - test
  - deploy preview

cache:
  paths:
    - node_modules/

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

show-var-prepare:
  stage: prepare
  script:
    - export
    - echo $BUILD_VERSION

# Build the code in local machine
yarn-build:
  stage: build
  script:
    - yarn

#Create runnable docker image and push in local registry
docker:
  stage: deploy preview
  image: docker:19
  services:
    - docker:19-dind
  script:
    - export VERSION=$(node -p "require('./package.json').version")
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$VERSION