version: '3.1'

services:
  mongo:
    image: mongo
    volumes:
      - /data/db
    networks:
      - app_net
  application:
    image: registry.gitlab.com/cmauri/twelvefactorapp:latest
    deploy:
      replicas: 10
    ports:
      - 80:3000
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: twelvefactor
      PORT: 3000
    networks:
      - app_net
    depends_on:
      - mongo
networks:
  app_net:
    external: false